server:
  port: 9009

spring:
  application:
    name: device-client

ws:
  server:
    secureHost: wss://${ws.host:localhost}/device-management-service/websocket
    host: ws://${ws.host:localhost}:${ws.port:8081}/websocket
    enableSSL: false
